; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
workspace_dir = ~/.srstuff/.pio            						;linux
;workspace_dir=c:/temp/platformio/.pio;

[env:cytron_maker_pi_rp2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git  
;board = cytron_maker_pi_rp2040                                  ;board ID for Cytron Maker Pi RP2040
;board = rpipico												; pico board
;board = rpipicow												; pico Wifi board
;board = rpipico2												; pico 2
;board = rpipico2w												; pico 2 Wifi board
board = cytron_motion_2350_pro		    						; Cytron Motion Pro 2350
;board = adafruit_trinkeyrp2040qt        						; Adafruit Trinkey QT2040 
framework = arduino                                             ; framework for Arduino              
board_build.core = earlephilhower                               ; Earle's Arduino core for Pico
lib_deps = https://github.com/dennisma/srbot.git       
monitor_filters =                                               ; monitor filters for serial monitor
	send_on_enter                                               ; waits until enter isA hit before sending over Serial
	time                                                        ; adds timestamp to serial output
	;log2file                                                    ; logs serial output to file
monitor_echo = true                                             ; echo serial monitor input
monitor_eol = CR                                                ; end of line character for serial monitor
;debug_tool = cmsis-dap											; last 4 lines set up debugging
;upload_protocol = cmsis-dap
;debug_speed = 30000
;build_type = debug
